# Generated by Django 4.1.13 on 2024-06-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_team_facebook_link_team_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='service_pics'),
        ),
    ]
