# Generated by Django 4.1.13 on 2024-06-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='service_pics')),
            ],
        ),
    ]
