# Generated by Django 4.1.13 on 2024-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(default='hello', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='testimonial_pics'),
        ),
    ]
